Numpy reshape shape to use *
pylint-dev/astroid pull request #1999
Opened 2023-01-31 15:43 UTC by clavedeluna

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
| ✓   | :sparkles: New feature |
| ✓   | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

## Description

Closes [#XXXX](https://github.com/PyCQA/pylint/issues/7883)

Pylint issue demonstrates a FP. I think this is the right solution, I also tested with this code and made sure pylint no longer showed the messages.

```
import numpy as np
x = np.zeros(12)
x.reshape(3, 2, 2)
x.reshape((3, 2))
x.reshape(3, 2, 2, order='F')
x.reshape(3, 2, 2, order='F')
x.reshape((3, 2, 2), order='F')

a = np.arange(6).reshape((3, 2))

x.reshape(a, order='F')

np.reshape(a, (2, 3))

np.reshape(a, 6, order='F')
```

2023-01-31 15:43 UTC, clavedeluna commented
I'm not really sure a unit test is needed here but if it does please let me know and hit to where it should be.

2023-02-05 21:36 UTC, DanielNoord commented on astroid/brain/brain_numpy_ndarray.py
> +        def reshape(self, *shape, order='C'): return np.ndarray([0, 0])
https://github.com/numpy/numpy/blob/9d7dca4596d7aeb8f31a261592a33d3b38b93b5f/numpy/__init__.pyi#L1767-L1774

The actual code is a bit different.. I'm not sure how to express this as it feels like we might run into issues with the other form as well..

2023-09-24 11:48 UTC, Pierre-Sassoulas requested changes
We install numpy during tests now, so it's possible to add automated tests for this (the example in the description at least).

2026-03-02 08:45 UTC, DanielNoord commented
@clavedeluna Any interest to pick this up again and add the test as asked for? :)

2026-03-04 14:36 UTC, clavedeluna commented on astroid/brain/brain_numpy_ndarray.py
> +        def reshape(self, *shape, order='C'): return np.ndarray([0, 0])
not sure if I need to address this? not sure what the ask

2026-03-04 15:01 UTC, Pierre-Sassoulas commented on astroid/brain/brain_numpy_ndarray.py
> +        def reshape(self, *shape, order='C'): return np.ndarray([0, 0])
I think Daniel's point is that there's multiple possible signature, and we only handle one here ?

2026-03-04 16:44 UTC, Pierre-Sassoulas reviewed
Tests lgtm for what we have but I'm not sure it handles every possible combination from the overload

2026-03-06 11:40 UTC, clavedeluna commented
@Pierre-Sassoulas I'm going to be away and won't get back to this so feel free to update it and merge

2026-03-06 11:45 UTC, DanielNoord commented on astroid/brain/brain_numpy_ndarray.py
> +        def reshape(self, *shape, order='C'): return np.ndarray([0, 0])
Yes, we still need to handle this difference in this PR.

2026-08-01 20:53 UTC, DanielNoord commented
Closing for now, we can always reopen later :)

See also https://github.com/pylint-dev/astroid/pull/2710 for our poor `numpy` support.

2026-08-01 20:53 UTC, closed without merging