Add deny list for modules to be skipped on AST generation
pylint-dev/astroid pull request #2399
Opened 2024-03-15 16:48 UTC by Jamie-

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :sparkles: New feature |

## Description

Adds `module_denylist` to `AstroidManager` for modules to be skipped during AST generation.
Modules in this list will cause an ``AstroidImportError`` to be raised when an AST for them is requested.

Refs pylint-dev/pylint#9442

2024-03-17 16:14 UTC, jacobtylerwalls submitted a review, later dismissed
Wonderful, thank you!

2024-03-18 09:57 UTC, Pierre-Sassoulas requested changes
Great first contribution, just a nit ! The core dump on python 3.10 on pypy is probably unrelated, (but also not flaky, so we need to check on main).

2024-03-18 09:57 UTC, Pierre-Sassoulas commented on astroid/manager.py
> +            raise AstroidImportError("Skipping ignored module")
```suggestion
            raise AstroidImportError(f"Skipping ignored module {modname!r}")
```

2024-03-18 09:57 UTC, Pierre-Sassoulas commented on tests/test_manager.py
> +        with pytest.raises(AstroidImportError):
```suggestion
        with pytest.raises(AstroidImportError, match="random"):
```

2024-03-20 12:01 UTC, Jamie- commented
Nits fixed :)

2024-03-20 12:06 UTC, Pierre-Sassoulas approved these changes

2024-03-25 13:24 UTC, merged