use the ClassDef attribute inference process in Instances
pylint-dev/astroid pull request #2563
Opened 2024-09-11 23:30 UTC by temyurchenko

A part of getting rid of non-Module roots, see #2536

Instances often have «special_attributes». ClassDef does a lot of
   transformations of attibutes during inference, so let's reuse them
   in Instance.

We are fixing inference of the "special" attributes of
   Instances. Before these changes, the FunctionDef attributes
   wouldn't get wrapped into a BoundMethod. This was facilitated by
   extracting the logic of inferring attributes into
   'FunctionDef._infer_attrs' and reusing it in BaseInstance.

  This issue isn't visible right now, because the special attributes
   are simply not found due not being attached to the parent (the
   instance). Which in turn is caused by not providing the actual
   parent in the constructor. Since we are on a quest to always
  provide a parent, this change is necessary.

2024-09-11 23:30 UTC, temyurchenko commented
Note that the biggest source of changes is just moving a bunch of code into a separate function

2024-09-15 12:54 UTC, DanielNoord requested changes

2024-09-15 12:54 UTC, DanielNoord commented on tests/test_scoped_nodes.py
> +        self.assertIsInstance(inferred[0], BoundMethod)
I think this change is incorrect, and therefore shows something is up with this PR.

To reproduce:
```python
class Clazz(object): ...


def func(arg1, arg2):
    "function that will be used as a method"
    return arg1.value + arg2


Clazz.m3 = func
inst = Clazz()
inst.m4 = func

print(Clazz.m3)
print(inst.m3)
print(inst.m4)
```


```shell
<function func at 0x109582340>
<bound method func of <__main__.Clazz object at 0x1095ab9b0>>
<function func at 0x109582340>
```

This should remain a `FunctionDef` and not a `BoundMethod`.

2024-09-25 07:38 UTC, temyurchenko commented
Closing in favour of #2584

2024-09-25 07:38 UTC, closed without merging